name: Release

on:
  push:
    branches:
      - develop
      - main

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build -c Release --no-restore

    
      - name: Start BPCalculator web app
        run: |
          dotnet run --project BPCalculator/BPCalculator.csproj --urls "http://localhost:5000" &
          echo "Waiting for app to start..."

          for i in {1..30}; do
            if curl -sSf http://localhost:5000 > /dev/null; then
              echo "App is up!"
              exit 0
            fi
            echo "Still waiting..."
            sleep 2
          done

          echo "App failed to start in time"
          exit 1

      
      - name: Install Playwright browsers
        working-directory: BP_E2E
        run: |
          dotnet build -c Release
          pwsh ./bin/Release/net8.0/playwright.ps1 install --with-deps

      
      - name: Run Unit Tests
        run: dotnet test -c Release --no-build --filter TestCategory!=E2E

      
      - name: Run Playwright E2E tests
        working-directory: BP_E2E
        run: dotnet test -c Release --no-build --filter TestCategory=E2E

      
      - name: Publish Application
        run: dotnet publish BPCalculator/BPCalculator.csproj -c Release -o ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bpapp
          path: ./publish

 
  deploy_qa:
    needs: build_and_package
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: bpapp
          path: ./publish

      - name: Deploy to QA Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bp-qa'  
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_QA }}
          package: ./publish

 
  deploy_prod:
    needs: build_and_package
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://bp-ca-prod.azurewebsites.net  

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: bpapp
          path: ./publish

      - name: Deploy to Production Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bp-ca-prod'  
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}
          package: ./publish
