name: Release

on:
  push:
    branches:
      - develop
      - main

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      

      - name: Publish app
        run: dotnet publish BPCalculator/BPCalculator.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bpapp
          path: ./publish

  deploy_qa:
    needs: build_and_package
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bpapp
          path: ./publish

      - name: Deploy to QA Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bp-qa'  
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_QA }}
          package: ./publish

  deploy_prod:
    needs: build_and_package
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://bp-ca-prod.azurewebsites.net 

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bpapp
          path: ./publish

      - name: Deploy to Prod Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bp-ca-prod'  
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}
          package: ./publish
